### ISSUE TITLE
Ability to delete entries

### ISSUE THREAD

**Issue by ChrstnMgcn** [b03tz/FormSave#2]
Thank you so much for this extra! It's incredibly helpful!

I haven't really run into any issues with it (that could be duplicated at least), but during testing I can tend to build up a lot of test form submissions and currently the only way to remove them is to go into the database directly. I have no problem with that myself, but I"m working on a form right now (to go live in 3 days) that our client will need to export the form submissions and remove them from the database daily. Is it possible to have that implemented?

Aside from that I can't think of anything else that would be needed. It's sooo helpful. Thanks again!

**Comment by b03tz** [comment]
I think this is in the new version...if it isn't I'll have to publish it still :) been a while!

**Comment by b03tz** [comment]
New version that has this feature will be published soon!

**Comment by labr1005** [comment]
Is this feature published and working? I can popup the context menu by right click but selecting "Delete" doesn't work...

Edit: I enabled the system setting "cache_db". That seems to be the problem. There aren't any records in the database, but they still show up in the manager. As soon as I disable this setting or clear the cache, everything is ok...

MODX 2.2.7
FormSave 1.1.0

Btw: The button "About / Upgrade" on the CMP doesn't show any content...
