### ISSUE TITLE
Field Content Sorting & Duplicate Detection

### ISSUE THREAD

**Issue by hephaestoskin** [b03tz/FormSave#3]
It would be amazingly helpful, especially to those running volunteer organizations, for the ability to sort the contacts by their field content.

Login/Subscribeme are great for those who want to mandate the creation of user accounts, but a lot of volunteer organizations prefer to just have their contact page dump into a database table. It would be great if there were an option that on export, would omit any duplicate entries of a certain form field.

Thanks, this extra as it is will be a HUGE help!

**Comment by b03tz** [comment]
This really is a custom feature, I will not implement this in the general version. If you want this contact me.
