### ISSUE TITLE
State checkboxes not saved

### ISSUE THREAD

**Issue by DonQuicky** [b03tz/FormSave#4]
I'am very very happy using this extra! Especially my customers use this extra with a smile {;o)=

I just discovered that in my forms the checkboxes show up as [[+value]] in FormSave back-end. I use the checkboxes as FormIt suggest to use is.

This seems a bug to me as the value of the checkboxes are showed fine in the e-mail-template.

**Comment by petkol** [comment]
I noticed the same thing. Actually the values go to database correctly but since they're stored as an array ["value1","value2"] they don't show up in the viewer.. 

Great Extra anyway, thanks a lot!

**Comment by audioroger** [comment]
It would be great to explode arrays so they show up in the viewer and exports.

**Comment by b03tz** [comment]
Issue is fixed, release will be soon!
