### ISSUE TITLE
Problems with special chars in csv export

### ISSUE THREAD

**Issue by exside** [b03tz/FormSave#6]
Hi,

first of all thanks for this nice extra, really helpful and saving a lot of time!

I noticed that special characters like a german "ä" are translated to unicode hex characters to save them in the db. When I export as print or xml, it works perfectly but when I do the same as CSV File I got a mess instead of the desired character.

Is there any possibility to have them saved as html entities and then decode them when exporting to csv? Or is there a direct function to convert hex unicode to "normal" characters?

thanks anyways for this nice extra!

Edit: It would also be a nice feature if we could pass in an array/comma seperated string with "Names" for the desired fields, so that we could customize the column names in the exported CSV File (now the column name is the name attribute of the input tag and this is not always convinient =D). And: Is there a possibility to disable the automatically added columns like the ID, IP and so on?

**Comment by b03tz** [comment]
As for disabling column read the manual usage on fsFormFields (you can specify which fields to save).
I will try to fix the encoding of the characters!

**Comment by b03tz** [comment]
Make sure when reading the CSV you set the language to UTF8, fixes your problem!
