### ISSUE TITLE
Error with creating form

### ISSUE THREAD

**Issue by ZieMenS** [b03tz/FormSave#7]
I have:
Modx Revo 2.2.1
FormIt  2.1.1

Aftre sucessfull installing FormSave package, i'm trying to add form in "FormSave" component, but after i fill "Name" & "Save these fields" fields => appears such error

"An error occurred while trying to save the form"

So i couldn't create any form = (

**Comment by b03tz** [comment]
In formsave you cannot create forms, you are mixing up components ;)
